### ISSUE TITLE
Possible ban

### ISSUE THREAD

**Issue by OtavioAugusto04** [tostercx/GTAO_Booster_PoC#6]
Since we are editing the game files, is it possible to get banned?

**Comment by mpql** [comment]
Yes. This is stated in the readme.

![image](https://user-images.githubusercontent.com/1709954/109541286-e0bfc980-7a80-11eb-99d2-6b56c1a8b2b0.png)

**Comment by patrickvrl** [comment]
But i'm pretty sure they will not ban you for this. You can spawn UFOs that you'll not be banned, but if you add money to your account, you'll get banned for sure. I guess they won't ban anyone for such a small fix

**Comment by OtavioAugusto04** [comment]
> But i'm pretty sure they will not ban you for this. You can spawn UFOs that you'll not be banned, but if you add money to your account, you'll get banned for sure. I guess they won't ban anyone for such a small fix

Sure, but as far as I know, mod menus in GTAO are not in game files, the ones that run inside the game always get detected. In this case we are literally adding files to the game.

**Comment by anazhd** [comment]
> > But i'm pretty sure they will not ban you for this. You can spawn UFOs that you'll not be banned, but if you add money to your account, you'll get banned for sure. I guess they won't ban anyone for such a small fix
> 
> Sure, but as far as I know, mod menus in GTAO are not in game files, the ones that run inside the game always get detected. In this case we are literally adding files to the game.

What you talking about?

More likely adding lines to the executables. Which will get unloaded after it run it, making the _rest_ of the process thereafter undistinguished by whatever approach T2 use to differ between normal unaltered runtime. If there's any though. Same thing goes to some mod menu that are still selling and operating until now, injection via kernel mapping etc. 

Some injector out there give pretty good solution to run JIT, hook and unhook. With t0st approach, you can't really go wrong unless you're doing it wrong. Still, don't do it if you are scared losing your virtual wealthy possession in GTAO. I'm waiting for R* to detect and ban my account for injecting this genius hash map that they can't figure out since 2015 (steam release). It would be a good giggle when many people brought this up on reddit. Time will tell.

_Yes T2 and R*, I'm looking on you guys for not implementing any good anti cheat solution which ruin online gameplay until today._
